### ISSUE TITLE
cannot compile on macosx 10.8.2

### ISSUE THREAD

**Issue by cofyc** [douban/beansdb#7]
```
make  all-recursive
Making all in doc
make[2]: Nothing to be done for `all'.
gcc -DHAVE_CONFIG_H -I.  -DNDEBUG   -I/opt/boxen/homebrew/include -MT beansdb-htree.o -MD -MP -MF .deps/beansdb-htree.Tpo -c -o beansdb-htree.o `test -f 'src/htree.c' || echo './'`src/htree.c
src/htree.c: In function ‘ht_open’:
src/htree.c:494: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘off_t’
src/htree.c:494: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘off_t’
src/htree.c:499: error: ‘POSIX_FADV_SEQUENTIAL’ undeclared (first use in this function)
src/htree.c:499: error: (Each undeclared identifier is reported only once
src/htree.c:499: error: for each function it appears in.)
make[2]: *** [beansdb-htree.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
